import pandas as pd
import io
from datetime import datetime

def export_cleaned_csv(df: pd.DataFrame) -> bytes:
    buffer = io.BytesIO()
    df.to_csv(buffer, index=False)
    return buffer.getvalue()

def export_insight_report(
    profile: dict,
    profile_analysis: str,
    cleaning_report: list,
    anomalies: list,
    insights: str,
    chart_specs: list
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    report = f"""# AI Data Copilot — Analysis Report
Generated: {now}

---

## Dataset Overview
- **Rows:** {profile['rows']}
- **Columns:** {profile['columns']}
- **Target Column:** {profile['guessed_target']}
- **Numeric Columns:** {', '.join(profile['numeric_cols'])}
- **Categorical Columns:** {', '.join(profile['categorical_cols'])}

---

## Profile Agent Analysis
{profile_analysis if profile_analysis else 'Not run'}

---

## Cleaning Report
"""
    if cleaning_report:
        for item in cleaning_report:
            report += f"- {item}\n"
    else:
        report += "- No cleaning performed\n"

    report += f"""
---

## Anomalies Detected
"""
    if anomalies:
        for item in anomalies:
            report += f"- {item}\n"
    else:
        report += "- No anomalies detected\n"

    report += f"""
---

## AI Recommended Charts
"""
    if chart_specs:
        for chart in chart_specs:
            report += f"- **{chart.get('title')}** — {chart.get('reason')}\n"
    else:
        report += "- No charts generated\n"

    report += f"""
---

## Business Insights & Recommendations
{insights if insights else 'Not run'}

---
*Generated by AI Data Operations Copilot*
"""
    return report