import pandas as pd
import io
from datetime import datetime

def export_cleaned_csv(df: pd.DataFrame) -> bytes:
    buffer = io.BytesIO()
    df.to_csv(buffer, index=False)
    return buffer.getvalue()

def export_insight_report(
    profile: dict,
    profile_analysis: str,
    cleaning_report: list,
    anomalies: list,
    insights: str,
    chart_specs: list
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    report = f"""# AI Data Copilot — Analysis Report
Generated: {now}

---

## Dataset Overview
- **Rows:** {profile['rows']}
- **Columns:** {profile['columns']}
- **Target Column:** {profile['guessed_target']}
- **Numeric Columns:** {', '.join(profile['numeric_cols'])}
- **Categorical Columns:** {', '.join(profile['categorical_cols'])}

---

## Profile Agent Analysis
{profile_analysis if profile_analysis else 'Not run'}

---

## Cleaning Report
"""
    if cleaning_report:
        for item in cleaning_report:
            report += f"- {item}\n"
    else:
        report += "- No cleaning performed\n"

    report += f"""
---

## Anomalies Detected
"""
    if anomalies:
        for item in anomalies:
            report += f"- {item}\n"
    else:
        report += "- No anomalies detected\n"

    report += f"""
---

## AI Recommended Charts
"""
    if chart_specs:
        for chart in chart_specs:
            report += f"- **{chart.get('title')}** — {chart.get('reason')}\n"
    else:
        report += "- No charts generated\n"

    report += f"""
---

## Business Insights & Recommendations
{insights if insights else 'Not run'}

---
*Generated by AI Data Operations Copilot*
"""
    return report


# ── Milestone 9: Export chat answers with citations ───────────────────────────

def export_chat_with_citations(
    chat_history: list,
    dataset_name: str = "dataset",
    knowledge_docs: list = [],
) -> str:
    """
    Export the full chat history as a markdown report with citations.

    Args:
        chat_history:  List of {"role": "user"|"assistant", "content": str}
        dataset_name:  Name of the uploaded CSV file.
        knowledge_docs: List of knowledge document filenames that were active.

    Returns:
        Markdown string ready for download.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# AI Data Copilot — Chat Report with Citations
Generated: {now}

---

## Session Context
- **Dataset:** `{dataset_name}`
- **Knowledge Documents Active:** {', '.join(f'`{d}`' for d in knowledge_docs) if knowledge_docs else 'None'}
- **Total Messages:** {len(chat_history)}

---

## Conversation

"""
    q_count = 1
    i = 0
    while i < len(chat_history):
        msg = chat_history[i]

        if msg["role"] == "user":
            report += f"### Q{q_count}: {msg['content']}\n\n"
            q_count += 1

            # Check if next message is assistant
            if i + 1 < len(chat_history) and chat_history[i + 1]["role"] == "assistant":
                answer = chat_history[i + 1]["content"]
                report += f"{answer}\n\n"

                # Extract any source citations mentioned in the answer
                citations = _extract_citations(answer, knowledge_docs)
                if citations:
                    report += "**Sources referenced in this answer:**\n"
                    for cite in citations:
                        report += f"- `{cite}`\n"
                    report += "\n"

                report += "---\n\n"
                i += 2
            else:
                i += 1
        else:
            i += 1

    report += "*Generated by AI Data Operations Copilot — V2 with RAG Knowledge Layer*\n"
    return report


def _extract_citations(answer: str, knowledge_docs: list) -> list:
    """
    Extract which knowledge documents were cited in an answer.
    Looks for document filenames mentioned anywhere in the answer text.

    Args:
        answer:        The assistant's answer string.
        knowledge_docs: List of knowledge document filenames.

    Returns:
        List of filenames that appear to be referenced in the answer.
    """
    cited = []
    answer_lower = answer.lower()

    for doc in knowledge_docs:
        # Check for full filename or name without extension
        doc_lower = doc.lower()
        doc_stem  = doc_lower.rsplit(".", 1)[0]   # e.g. "cybersecurity_policy"
        if doc_lower in answer_lower or doc_stem in answer_lower:
            cited.append(doc)

    # Also catch generic "knowledge source" references
    if "knowledge source" in answer_lower and not cited and knowledge_docs:
        cited = knowledge_docs  # all docs were potentially used

    return cited